stable:
  image: rust:1-slim
  script:
    - cargo test
    - rustup component add rustfmt
    - cargo fmt -- --check

nightly:
  image: rustlang/rust:nightly
  script: cargo test
  allow_failure: true
